# Generated by Django 3.1.2 on 2020-10-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_staffr',
            new_name='is_staff',
        ),
    ]
